git:
  remote:
    upstream: 'mongodb/docs-cxx'
    tools: 'mongodb/docs-tools'
project:
  name: 'driver-cxx'
  tag: 'driver-cxx'
  url: 'http://docs.mongodb.com'
  title: "C++ Driver Manual"
  branched: false
system:
  tools:
    ref: HEAD
    pinned: false
  make:
    generated:
      - 'sphinx'
      - 'meta'
      - 'migrations'
      - 'integration'
    static:
      - 'makefile.compatibility'
      - 'makefile.clean'
  files:
    - 'integration.yaml'
    - 'sphinx_local.yaml'
    - htaccess: ['htaccess.yaml']
version:
  release: '2.6.4'
  branch: '2.6'
assets:
paths:
  output: 'build'
  source: 'source'
  includes: 'source/includes'
  images: 'source/images'
  tools: 'bin'
  buildsystem: 'docs-tools'
  builddata: 'config'
...
