project: 'mongodb-compass'
master_doc: 'index'
paths:
  static: ['source/.static']
theme:
  name: 'ecosystem'
  sitename: 'C++ Driver Manual'
  jira: 'DOCS'
  google_analytics: 'UA-7301842-8'
  nav_excluded:
    - /
    - /reference
    - /tutorials
sidebars:
  '**':
    - 'pagenav.html'
...
